sudo: required
services: docker
script:
  - docker build -t fifths/php:7.3.11-fpm ./7.3/7.3.11/alpine3.10/fpm
  - docker build -t fifths/php:7.3.11-cli ./7.3/7.3.11/alpine3.10/cli
after_script:
  - docker images
